Repository AndrewGPFranco/API_PlataformaV2, pull requests merged in 2024-06, with the labels that each got.

#7 Utilizando flyway para gerenciar as migrations.
  pom.xml
  src/main/resources/db/migration/V1__create_table_aula.sql
  src/main/resources/db/migration/V2__create_table_curso.sql
  src/main/resources/db/migration/V3__create_table_aluno.sql
  src/main/resources/db/migration/V4__create_table_usuarios.sql
Labels: Esforço-1, Melhoria, In-Resolved

#8 Funcionalidade para cadastrar usuário criada, funcionando e testada.
  src/main/java/com/gpf/ti/controller/UserController.java
  src/main/java/com/gpf/ti/dtos/usuario/UserDto.java
  src/main/java/com/gpf/ti/exception/FormatoInvalidoException.java
  src/main/java/com/gpf/ti/exception/SenhaComPoucosCaracteresException.java
  src/main/java/com/gpf/ti/infra/security/SecurityConfigurations.java
  src/main/java/com/gpf/ti/model/Usuario.java
  src/main/java/com/gpf/ti/repository/UsuarioRepository.java
  src/main/java/com/gpf/ti/services/AutenticacaoService.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V4__create_table_usuarios.sql
Labels: Esforço-3, Novidade, Resolved

#10 Adicionado novos campos para cadastro de usuário.
  src/main/java/com/gpf/ti/dtos/usuario/UserDto.java
  src/main/java/com/gpf/ti/enums/GeneroType.java
  src/main/java/com/gpf/ti/model/Usuario.java
  src/main/java/com/gpf/ti/repository/UsuarioRepository.java
  src/main/java/com/gpf/ti/services/AutenticacaoService.java
  src/main/resources/db/migration/V5__alter_table_usuarios.sql
  src/main/resources/db/migration/V6__alter_table_usuarios.sql
Labels: Esforço-2, Melhoria, In-Review, Fire

#14 Tornando telefone atributo unico
  src/main/java/com/gpf/ti/dtos/usuario/UserDto.java
  src/main/resources/db/migration/V5__alter_table_usuarios.sql
Labels: Esforço-1, Resolved, Fire

#16 Docker adicionado no projeto para banco de dados
  docker-compose.yml
  pom.xml
  src/main/resources/application.properties
Labels: Esforço-3, Novidade, Melhoria, Resolved

#18 9 tornar a dashboard dinâmica
  src/main/java/com/gpf/ti/controller/AutenticacaoController.java
  src/main/java/com/gpf/ti/dtos/infra/DadosTokenJwtDto.java
  src/main/java/com/gpf/ti/dtos/infra/DadosUsuario.java
  src/main/java/com/gpf/ti/dtos/infra/DadosUsuarioIsAdmin.java
  src/main/java/com/gpf/ti/model/Usuario.java
  src/main/java/com/gpf/ti/services/AutenticacaoService.java
Labels: Esforço-1, Melhoria, Resolved

#19 Remover entidade aluno
  src/main/java/com/gpf/ti/controller/AlunoController.java
  src/main/java/com/gpf/ti/controller/AutenticacaoController.java
  src/main/java/com/gpf/ti/dtos/aluno/AlunoDto.java
  src/main/java/com/gpf/ti/dtos/infra/DadosUsuario.java
  src/main/java/com/gpf/ti/dtos/usuario/UserDto.java
  src/main/java/com/gpf/ti/mappers/AlunoMapper.java
  src/main/java/com/gpf/ti/model/Aluno.java
  src/main/java/com/gpf/ti/model/Usuario.java
  src/main/java/com/gpf/ti/repository/AlunoRepository.java
  src/main/java/com/gpf/ti/repository/UsuarioRepository.java
  src/main/java/com/gpf/ti/services/AlunoService.java
  src/main/java/com/gpf/ti/services/AutenticacaoService.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V10__alter_table_usuarios.sql
  src/main/resources/db/migration/V8__drop_table_aluno.sql
  src/main/resources/db/migration/V9__alter_table_usuarios.sql
Labels: Esforço-1, Melhoria, In-Progress

#20 Sistema de recomendação de vídeos
  src/main/java/com/gpf/ti/config/RepairMigration.java
  src/main/java/com/gpf/ti/controller/AulaController.java
  src/main/java/com/gpf/ti/model/Aula.java
  src/main/java/com/gpf/ti/repository/AulaRepository.java
  src/main/java/com/gpf/ti/services/AulaService.java
  src/main/resources/db/migration/V11__alter_table_aula.sql
Labels: Esforço-3, Novidade, Resolved
